@echo off
echo Compiling...
gcc -o play assets/icon/icon.o src/*.c -lncurses -Wall -Werror -Wpedantic -O3 -ljson-c -fstack-protector -C -H -trigraphs
echo Changing MZ header...
powershell -noprofile -executionpolicy bypass -file ./scripts/textalteration.ps1
echo Editing files...
echo Done.
